name: TiszaBuilder
main: hu.ikoli.tiszabuilder.TiszaBuilder
version: 1.0
api-version: 1.21
author: ikoli, Ris
soft-depend: [PlaceholderAPI]
depend: [LocaleLib]

libraries:
  - redis.clients:jedis:4.4.0

commands:
  tiszabuilder:
    aliases: [b, builder]
